### ISSUE TITLE
kmer_prism crashes on some tag count files 

### ISSUE THREAD

**Issue by afmcc** [AgResearch/data_prism#1]
Traceback (most recent call last):
  File "/dataset/hiseq/active/bin/DECONVQC/kmer_prism.py", line 469, in <module>
    main()
  File "/dataset/hiseq/active/bin/DECONVQC/kmer_prism.py", line 461, in main
    distributions = build_kmer_distributions(options)
  File "/dataset/hiseq/active/bin/DECONVQC/kmer_prism.py", line 289, in build_kmer_distributions
    options["kmer_size"], options["input_driver_config"]))
  File "/dataset/hiseq/active/bin/DECONVQC/kmer_prism.py", line 251, in build_kmer_distribution
    distdata = build(distob, use="singlethread")
  File "/bifo/active/hiseq/bin/DECONVQC/data_prism.py", line 862, in build
    results.append(build_part(arg))
  File "/bifo/active/hiseq/bin/DECONVQC/data_prism.py", line 836, in build_part
    return distob.get_partial_distribution(slice_number)
  File "/bifo/active/hiseq/bin/DECONVQC/data_prism.py", line 139, in get_partial_distribution
    raw_values = self.get_raw_values_stream()
  File "/bifo/active/hiseq/bin/DECONVQC/data_prism.py", line 120, in get_raw_values_stream
    file_streams = [self.file_to_stream_func(filename, *self.file_to_stream_func_xargs) for filename in self.input_filenames]
  File "/dataset/hiseq/active/bin/DECONVQC/kmer_prism.py", line 145, in tag_count_from_tag_count_file
    while( common_prefix_length < min(len(sorted_tuples[0]), len(sorted_tuples[-1])) ):
IndexError: list index out of range

**Comment by afmcc** [comment]
(relates to some odd data under 180607_D00390_0368_BCCJJVANXX/SQ0705)
